### ISSUE TITLE
Loading Resource for IT is broken

### ISSUE THREAD

**Issue by manumaticx** [impure/auto_hyphenating_text#15]
Once, [this issue](https://github.com/nikitadol/hyphenator/issues/10) is fixed in `hyphenator` the dependency has to be updated

**Comment by manumaticx** [comment]
Ah I see, this is the wrong dependency ... you will also have to update your fork:
https://github.com/impure/hyphenator

I didn't see that it was re-published with another name

**Comment by Allyanora** [comment]
Just checked, unfortunately both italian assets have the same typo

![image](https://github.com/impure/auto_hyphenating_text/assets/907444/e40e4c5f-23a5-4796-a5fb-985b6213a495)

**Comment by manumaticx** [comment]
ping

**Comment by impure** [comment]
Run a `flutter upgrade` It should be fixed in the dependency. If it's not I'll have to look into it.

**Comment by manumaticx** [comment]
`flutter upgrade` does not change dependencies - it upgrades the local flutter version.

**Comment by manumaticx** [comment]
Yes, thanks. 

`flutter pub upgrade` did upgrade [hyphenator_impure](https://pub.dev/packages/hyphenator_impure) to 0.1.4

I was just a little bit confused where that new version come from
