### ISSUE TITLE
Performance and Compatibility Issues

### ISSUE THREAD

**Issue by CYXiang** [impure/auto_hyphenating_text#17]
First and foremost, I'd like to express my sincere gratitude to the author for providing these insights. However, upon attempting to use this library, I encountered two significant issues: 1) Severe performance problems when dealing with German text, and 2) Incompatibility with IntrinsicHeight at the parent level, as the internal LayoutBuilder fails to calculate the height correctly.

Proposed Solutions
1. Initialize and cache the Hyphenator locally during the initial setup, rather than repeatedly initializing it within the LayoutBuilder.

2. Within the LayoutBuilder, if the constraints remain unchanged, directly retrieve the cached Widget instead of recalculating.

3. To address the issue with IntrinsicHeight at the parent level, consider adding a parameter that allows manual setting of constraints from the outside, eliminating the need for a LayoutBuilder.

I welcome any additional ideas from the author or insights into aspects I may have overlooked.

**Comment by impure** [comment]
OK, it looks like the Hyphenator is doing an operation on a large list of strings so I guess it's worth caching. I moved this to initState(). I'm not sure about the other solutions though. You could wrap the widget in a sized box to force a size and caching widgets introduces the risk that it doesn't update properly (such as when changing to dark mode).

**Comment by CYXiang** [comment]
fixed, cheers
