### ISSUE TITLE
Duplicate hyphen for words that already include a hyphen

### ISSUE THREAD

**Issue by ChristopherKL** [impure/auto_hyphenating_text#2]
Hello,
first of all, thanks for the great work you did with this package.
I'm using the de1996 hyphenation and it's producing duplicate hyphens when the string already has one hyphen inside a word. Is there a way to prevent this?

![Duplicate hyphen](https://user-images.githubusercontent.com/27887612/225014912-891970db-da96-4705-b4f0-9ed6d49559f4.png)

Package version: 0.0.4
Flutter version: 3.3.10

**Comment by impure** [comment]
OK, I changed it so now if the last character is any punctuation character it will not add a hyphen.

**Comment by ChristopherKL** [comment]
Thank you for the fast response. I will update the package today and test it.
