### ISSUE TITLE
setting maxline 2 and textoverflow is not affecting/working

### ISSUE THREAD

**Issue by FaisalMohammadi** [impure/auto_hyphenating_text#4]

**Comment by impure** [comment]
OK, I fixed a bug where max lines was not working properly if we hyphenate the text.

**Comment by FaisalMohammadi** [comment]
Perfect i can confirm that the bug is now fixed thank you.

**Comment by FaisalMohammadi** [comment]
One more thing, when i want to set the textOverflow to ellipsis or anything, its not affecting. I will open a new issue for this. Anyway thank you for your quick response.
