### ISSUE TITLE
Feature: selectable text

### ISSUE THREAD

**Issue by FaisalMohammadi** [impure/auto_hyphenating_text#6]
it would be very nice if their is an option to enable the selectable text feature of flutter, i am using selectableText widget everywhere in my code and now i need also hyphenation and right now i am not able to use it bothe together.

**Comment by impure** [comment]
The problem with that is there will be random new lines in the text. So I'm not really sure how to do it.

**Comment by FaisalMohammadi** [comment]
I lookes in your code you are using richtext and textspans everywhere can you not mabe just use SelectableText.rich instead?

**Comment by Pherne** [comment]
Hello,

if this is still an issue you can try my fork: https://github.com/Pherne/auto_hyphenating_text 

I also created a PR in case you don't want to use random forks in your project IF it gets accepted at all.

**Comment by FaisalMohammadi** [comment]
Thats great man @Pherne thank you. For now i just forked your version and it works perfectly fine, but still looking for your pull request to be merged by @impure.
