### ISSUE TITLE
Custom separator

### ISSUE THREAD

**Issue by merfire** [impure/auto_hyphenating_text#7]
Currently, the only separator string is U+2010 dash "‐", in my case this is causing problems specifically with Poppins font.

<img width="308" alt="Screenshot 2023-05-16 at 13 07 48" src="https://github.com/impure/auto_hyphenating_text/assets/21159950/049c9e1f-9f05-4c80-95bc-710eb24f53d8">

It's rendered at the bottom of the characters, I've tried regular dash "-", and that works properly, issue here is U+2010 dash "‐".
I would suggest having a way to pass whatever separator string/char we want as a separator, and maybe changing the default one to regular dash, and not U+2010 dash.

**Comment by ZaidrazaNarsinh** [comment]
@merfire I made some changes to the code locally to achieve this. I will try to fork the repository and generate a pull request by tomorrow. I will provide the GitHub link here so that you can use it.

**Comment by merfire** [comment]
Thank you for adding this feature 👍🏻
